from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.adventure_index,
        name='adventures'
    ),
    path(
        'adventure/view/<int:id>',
        views.adventure_view,
        name='adventure_view'
    ),
    path(
        'adventure/add',
        views.adventure_add,
        name='adventure_add'
    ),
    path(
        'adventure/edit/<int:id>',
        views.adventure_edit,
        name='adventure_edit'
    ),
    path(
        'adventure/delete/<int:id>',
        views.adventure_delete,
        name='adventure_delete'
    ),
    path(
        'mission/add/<int:adventure_id>',
        views.mission_add,
        name='mission_add'
    ),
    path(
        'mission/edit/<int:id>',
        views.mission_edit,
        name='mission_edit'
    ),
    path(
        'mission/delete/<int:id>',
        views.mission_delete,
        name='mission_delete'
    ),
    path(
        'submission/add/<int:parent_id>/<int:adventure_id>',
        views.submission_add,
        name='submission_add'
    )
]
