# Generated by Django 5.2.4 on 2025-09-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('adventures', '0001_initial'), ('adventures', '0002_mission_completed'), ('adventures', '0003_alter_adventure_description_alter_mission_name_and_more'), ('adventures', '0004_alter_adventure_description_alter_mission_notes'), ('adventures', '0005_alter_adventure_description_alter_mission_notes'), ('adventures', '0006_rename_mission_mission_adventure'), ('adventures', '0007_alter_adventure_description_alter_mission_notes'), ('adventures', '0008_alter_adventure_name_alter_mission_name'), ('adventures', '0009_mission_parent'), ('adventures', '0010_alter_adventure_name_alter_mission_name'), ('adventures', '0011_alter_mission_name'), ('adventures', '0012_alter_mission_adventure'), ('adventures', '0013_alter_adventure_description_alter_mission_notes'), ('adventures', '0014_alter_adventure_options'), ('adventures', '0015_alter_adventure_description_alter_mission_notes'), ('adventures', '0016_alter_adventure_options_alter_adventure_description_and_more'), ('adventures', '0017_alter_adventure_options_alter_adventure_description_and_more'), ('adventures', '0018_alter_mission_completed'), ('adventures', '0019_alter_mission_completed'), ('adventures', '0020_alter_mission_name'), ('adventures', '0021_alter_adventure_description_alter_mission_name')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('notes', models.CharField(blank=True, max_length=512, null=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='adventures.adventure')),
                ('completed', models.CharField(choices=[('N', 'No'), ('Y', 'Yes'), ('I', 'Impossible')], default='N', max_length=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='adventures.mission')),
            ],
        ),
    ]
