# Generated by Django 5.2.4 on 2025-10-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('notes', models.CharField(blank=True, max_length=512, null=True)),
                ('completed', models.CharField(choices=[('N', 'No'), ('Y', 'Yes'), ('I', 'Impossible')], default='N', max_length=1)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='adventures.adventure')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='adventures.mission')),
            ],
        ),
    ]
