# Generated by Django 5.2.4 on 2025-10-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
