# Generated by Django 5.2.4 on 2026-01-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_mission_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
