# Generated by Django 5.2.4 on 2026-01-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_alter_mission_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['position']},
        ),
    ]
